version: '3'
services:
  djdemo:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/code
    ports:
      - "0.0.0.0:8000:8000"
    depends_on:
      - mysql
    links:
      - mysql
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=5678
